using System;
using AutoPropertyGenerator;

[AutoProperty]
public partial class MyClass
{
}

class Program
{
    static void Main()
    {
        var obj = new MyClass();
        Console.WriteLine(obj.AutoGeneratedProperty);
    }
}
